[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log

[program:laravel-migrate]
command=php /var/www/html/artisan migrate --force
autostart=true
autorestart=false
startsecs=0
stdout_logfile=/var/log/supervisor/migrate.log
redirect_stderr=true

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true

[program:laravel-queue]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/queue.log
